### ISSUE TITLE
how to solve this error?

### ISSUE THREAD

**Issue by crylg** [dave3d/dicom2stl#2]
**C:\Users\Leiguan>easy_install SimpleITK**
Searching for SimpleITK
Best match: SimpleITK 0.10.0
Adding SimpleITK 0.10.0 to easy-install.pth file

Using c:\users\leiguan\appdata\local\programs\python\python35-32\lib\site-packages
Processing dependencies for SimpleITK
Finished processing dependencies for SimpleITK

**D:\dicom2stl>vtkpython dicom2stl.py -t bone -o bone.stl dicom.zip**

Temp dir:  c:\users\leiguan\appdata\local\temp\tmp5alcic
Tissue type:  bone
Thresholds:  [200.0, 800.0, 1300.0, 1500.0]
File names:  ['dicom.zip']

Traceback (most recent call last):
  File "dicom2stl.py", line 224, in <module>
    import SimpleITK as sitk
ImportError: No module named SimpleITK

**Comment by cogitas3d** [comment]
Hi @crylg !

To solve this you have to install SimpleITK package.

You will found informations here: https://itk.org/Wiki/SimpleITK/GettingStarted

A big hug!

**Comment by Sachingit1389** [comment]
How to solve this error ? Not getting whats going wrong?Why this AttributeError is coming?

C:\Users\Admin\Desktop\sachin>python C:\Users\Admin\Desktop\sachin\dicom2stl.py dicom.zip
Temp dir:  C:\Users\Admin\AppData\Local\Temp\tmpknar9hfu
Isovalue =  0
File names:  ['dicom.zip']

Reading Dicom zip file: dicom.zip
1.76.380.18.10.5944.11594.2.1 C:\Users\Admin\AppData\Local\Temp\tmpknar9hfu\Dicomm 483

Loading series 1.76.380.18.10.5944.11594.2.1 in directory C:\Users\Admin\AppData\Local\Temp\tmpknar9hfu\Dicomm
Shrink factors:  [2, 2, 2]
(498, 484, 483) -> (249, 242, 241)
     0.093 seconds
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\sachin\dicom2stl.py", line 398, in <module>
    import sitk2vtk
  File "C:\Users\Admin\Desktop\sachin\sitk2vtk.py", line 22, in <module>
    pixelmap = { sitk.sitkUInt8:   vtk.VTK_UNSIGNED_CHAR,  sitk.sitkInt8:    vtk.VTK_CHAR,
AttributeError: 'module' object has no attribute 'VTK_UNSIGNED_CHAR'

Why this AttributeError is coming?
