### ISSUE TITLE
Comparing physical sizes of different generated meshes

### ISSUE THREAD

**Issue by TviNet** [dave3d/dicom2stl#33]
I have found this tool incredibly useful for extracting 3D meshes from different DICOM sources. However, the relative physical size of different meshes is sometimes different. While the STL file is dimensionless, is there a way to scale the resulting meshes such that their relative sizes reflect the real world? 

I assume this should be possible since the DICOM files store pixels to real-world coordinate conversion but I am not too familiar with VTK.

**Comment by dave3d** [comment]
Let me check on it.  It should be do-able.  I think it's a matter of transforming the mesh points from volume space to world space using the volume's transform.

**Comment by TviNet** [comment]
I tried to find a transform that I can apply to the mesh but I am unable to figure this out. 

For two example meshes I printed the vtkImageData and vtkPolyData information. (vtkImageData is obtained after the sitk2vtk step and vtkPolyData after the extractSurface using vtkContourFilter)
Shown here are parts that I think are relevant. 
The bounds don't make sense to me. The Y axis bound seem to neither be in the voxel (exceed 522) or world coordinates (exceed 147/254).

```
Mesh1:
    vtkImageData:
        Bounds:
            Xmin,Xmax: (-147.322, 146.758)
            Ymin,Ymax: (-147.322, 146.758)
            Zmin,Zmax: (-52.25, 130.25)
        Spacing: (0.564453, 0.564453, 2.5)
        Origin: (-147.322, 146.758, -52.25)
        Dimensions: (522, 522, 74)
    vtkPolyData:
        Bounds:
            Xmin,Xmax: (-71.5439, 68.1571)
            Ymin,Ymax: (222.536, 418.118)
            Zmin,Zmax: (-41.6225, 109.623)
        Number Of Points: 555958


Mesh2:
    vtkImageData:
        Bounds:
            Xmin,Xmax: (-254.883, 253.906)
            Ymin,Ymax: (-254.883, 253.906)
            Zmin,Zmax: (-118.77, 64.35)
        Spacing: (0.976562, 0.976562, 3.27)
        Origin: (-254.883, 253.906, -118.77)
        Dimensions: (522, 522, 57)
    vtkPolyData:
        Bounds:
            Xmin,Xmax: (-80.8097, 66.161)
            Ymin,Ymax: (414.307, 630.614)
            Zmin,Zmax: (-104.869, 47.1793)
        Number Of Points: 185126
```

**Comment by dave3d** [comment]
Something wacky is going on there.  The X and Z ranges of your meshes are contained within the volume ranges, as they should be.  But the Y ranges are not.

But the mesh coordinates are certainly not in volume space, otherwise they would range within your voxel index ranges, i.e. not be negative numbers.

**Comment by dave3d** [comment]
Oh, the one thing I don't see is the Direction vector for the vtkImageData objects.  the Origin, Spacing, and Direction define the geometry of the image in world space.  The transform is defined be the Origin and the Direction.

**Comment by TviNet** [comment]
The Direction vector for both is  
Direction: (1, 0, 0, 0, -1, 0, 0, 0, 1)

Would this mean that vtkPolyData is already in world coordinates and so the scaling is accurate?

**Comment by TviNet** [comment]
I have updated my earlier comment with the values for the following example meshes. 
I have the output stl mesh on the top and the dicom visualized below. Mesh1 is on the left and Mesh2 is on the right.
If the values are not in volume space (due to negative numbers), then the world space still seems to be on a different scale.

<img src="https://user-images.githubusercontent.com/24621183/148698865-12fecc52-09bc-43a8-b2ea-f8f9281150a6.png" width="225" height="200" />
<img src="https://user-images.githubusercontent.com/24621183/148698867-2dd88de3-5490-49ed-bb3d-933c63b2638c.png" width="225" height="200" />

**Comment by dave3d** [comment]
It clearly isn't properly handling the negative Y row in the direction vector.  I'll see if I can make a similar example and figure out why.  A possible work-around, for now, is to flip the sign of all the Y values in the vertices of the meshes.

**Comment by dave3d** [comment]
I've look into it a bit, and I think VTK is not properly using the image's direction information when doing iso-surface extraction.  VTK only started even keeping a direction vector field for images with version 9, so it wouldn't surprise me if there are issues.  I will investigate it further and see if I can fix it. Or I could write a script to work around the problem.
