### ISSUE TITLE
Sample .DCM files available? (Does not work on my .DCM files)

### ISSUE THREAD

**Issue by hegde00** [dave3d/dicom2stl#35]
Hello,

Are there sample .DCM files on which this script works, please?  I ask because it does not seem to work on any of our .DCM files (brain T1 images).

Thank you very much!

**Comment by dave3d** [comment]
Certainly folks have used it on DICOM.  It's the back-end for the NIH 3d Print Exchange, where people submit DICOM to 3d printing purposes.  Can you share a data-set with me so I can check out what's going wrong?

**Comment by dave3d** [comment]
Note that the tissue-type settings are designed for CT images.  For MRI you're going to have to select an iso-value yourself.

**Comment by hegde00** [comment]
Thank you very much. That was very helpful. We determined the iso-value for our images and re-ran it, and it worked beautifully and created an STL mesh of the head. So please consider that problem solved, and thank you very much for the suggestion!

However, we have encountered the another problem. Your README.md says that the script "...can read any format supported by ITK." Since ITK supports NII (our preferred data format), we tried to run it on a .NII file, but it doesn't work. I attach the log. (The log uses the .nii file downloaded from:  https://data.idoimaging.com/nifti/1010_brain_mr_02.nii.gz.  But we'll be happy to share our own data with you if you prefer.  Please let me know if you'd like us to do that.)

Could you please look at what we're doing wrong, please?

Thank you very much,
Jay

[dicom2stl.py_LOG_JayHegde_07Mar2022.txt](https://github.com/dave3d/dicom2stl/files/8201691/dicom2stl.py_LOG_JayHegde_07Mar2022.txt)

**Comment by dave3d** [comment]
I was able to run the script on your Nifty file ok.  When you ran it, you used the '-t bone' option, which, as I said, uses pre-set CT parameters.  Here's how I ran it:

dicom2stl.py -i 150 --reduce .1 -o result.stl 1010_brain_mr_02.nii.gz

And the results I got:
<img width="609" alt="Screen Shot 2022-03-08 at 2 24 30 PM" src="https://user-images.githubusercontent.com/611581/157310309-ffccdf61-f04c-49ea-b922-ea322cb3191f.png">

**Comment by hegde00** [comment]
Ah, we were just making a silly mistake. Thank you very much for clearing it up! Sorry to trouble you without 'doing our homework', as it were.
Jay

**Comment by dave3d** [comment]
No problem.  I hope that the tool works for you.  Let me know if you have any other issues or questions.
