### ISSUE TITLE
server side ? 

### ISSUE THREAD

**Issue by Chyper00** [dave3d/dicom2stl#4]
can i put this in an node server ? 
make a post request 
and download the data converted 

many thanks

**Comment by dave3d** [comment]
Sure, you ought to be able to do it.  You'd need to install the required packages on the server, primarily SimpleITK and vtk.

That's pretty much what the NIH 3d Print Exchange does.  It's using my script on the server.

**Comment by Chyper00** [comment]
Any tips how to start ? 
i really im newbi at server side stuffs
