### ISSUE TITLE
'loadLargestSeries' is not defined

### ISSUE THREAD

**Issue by skotecha999** [dave3d/dicom2stl#9]
C:\Users\Suraj\Documents\GitHub\dicom2stl>vtkpython dicom2stl.py -t bone -o bone.stl dicom

Temp dir:  C:\Users\Suraj\AppData\Local\Temp\tmp0axtfnc7
Tissue type:  bone
Thresholds:  [200.0, 800.0, 1300.0, 1500.0]
Traceback (most recent call last):
  File "dicom2stl.py", line 277, in <module>
    img, modality = loadLargestSeries(fname[0])
NameError: name 'loadLargestSeries' is not defined

cannot figure out a way to resolve this 
already installed vtk and SimpleITK

C:\Users\Suraj\Documents\GitHub\dicom2stl>pip install SimpleITK
Collecting SimpleITK
  Downloading SimpleITK-1.2.4-cp37-cp37m-win_amd64.whl (28.0 MB)
     |████████████████████████████████| 28.0 MB 930 kB/s
Installing collected packages: SimpleITK
Successfully installed SimpleITK-1.2.4

conda install -c anaconda vtk
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

C:\Windows\system32>pip install vtk
Requirement already satisfied: vtk in c:\users\suraj\anaconda3\lib\site-packages (-PKG-VERSION)

**Comment by dave3d** [comment]
Thanks.  I've been re-organizing the code and forgot a package reference.

I've just updated the code and hopefully it should work now.  Let me know if it does.

**Comment by skotecha999** [comment]
just tested the bone rendering, works fine when the dicom images are in a zip but throws the same error when the images are in a directory folder.

P.S can you help me with setting the parameters such that a 3D model of just the large intestine(Colon) is generated

**Comment by dave3d** [comment]
That ModuleNotFoundError looks like a problem with your Python/VTK setup.  The module loader cannot find the module vtkRenderingFreeTypePython.  What version of VTK are you using and how did you install it?

**Comment by skotecha999** [comment]
(Resolved)
The package was insalled in anaconda.. the program runs fine in the anaconda prompt.

P.S is there any way to isolate the colon and create a volume render

**Comment by pjaol** [comment]
First this is awesome thank you for releasing this.
I wanted to take an old MRI I had an create an STL out of it to 3d print, and started pulling my hair out trying to figure out how to do an ROI to extract a skull. 

Ran into the loadLargestSeries as well, and made some minor code changes to fix this and python 3 deprecated issues. they are in pull request #11 
Would be great if you could include that
